#r @"C:\Users\rvino\.nuget\packages\benchmarkdotnet.annotations\0.13.2\lib\netstandard2.0\BenchmarkDotNet.Annotations.dll"
#r @"C:\Users\rvino\.nuget\packages\benchmarkdotnet\0.13.2\lib\net6.0\BenchmarkDotNet.dll"
#r @"C:\Users\rvino\.nuget\packages\commandlineparser\2.4.3\lib\netstandard2.0\CommandLine.dll"
#r @"C:\Users\rvino\.nuget\packages\dapper.fsharp\3.3.0\lib\net5.0\Dapper.FSharp.dll"
#r @"C:\Users\rvino\.nuget\packages\dapper\2.0.123\lib\net5.0\Dapper.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.0.2\lib\netstandard2.0\Dia2Lib.dll"
#r @"c:\prj\DotNetGraph\Sources\DotNetGraph\bin\Debug\netstandard2.0\DotNetGraph.dll"
#r @"C:\Users\rvino\.nuget\packages\entityframework\6.4.4\lib\netstandard2.1\EntityFramework.SqlServer.dll"
#r @"C:\Users\rvino\.nuget\packages\entityframework\6.4.4\lib\netstandard2.1\EntityFramework.dll"
#r @"C:\Users\rvino\.nuget\packages\sqlprovider\1.3.1\lib\netstandard2.0\FSharp.Data.SqlProvider.dll"
#r @"C:\Users\rvino\.nuget\packages\fsunit\5.2.0\lib\net7.0\FsUnit.NUnit.dll"
#r @"C:\Users\rvino\.nuget\packages\giraffe.viewengine\1.4.0\lib\net5.0\Giraffe.ViewEngine.dll"
#r @"C:\Users\rvino\.nuget\packages\graphviz.net\1.0.0\lib\net40\GraphVizWrapper.dll"
#r @"C:\Users\rvino\.nuget\packages\iced\1.17.0\lib\netstandard2.1\Iced.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.bcl.asyncinterfaces\1.1.0\ref\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\Microsoft.CSharp.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.codeanalysis.csharp\3.0.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.codeanalysis.common\3.0.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.0.2\lib\netstandard2.0\Microsoft.Diagnostics.FastSerialization.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.netcore.client\0.2.251802\lib\netcoreapp3.1\Microsoft.Diagnostics.NETCore.Client.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.runtime\2.2.332302\lib\net6.0\Microsoft.Diagnostics.Runtime.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.0.2\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.dotnet.platformabstractions\3.1.6\lib\netstandard2.0\Microsoft.DotNet.PlatformAbstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.configuration.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.configuration.binder\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.configuration\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.Logging.Abstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.logging\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Logging.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.options\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Options.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.extensions.primitives\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CommunicationUtilities.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CoreUtilities.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CrossPlatEngine.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.TestPlatform.PlatformAbstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.TestPlatform.Utilities.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\Microsoft.VisualBasic.Core.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\Microsoft.VisualBasic.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.codecoverage\17.4.0\lib\netcoreapp3.1\Microsoft.VisualStudio.CodeCoverage.Shim.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.VisualStudio.TestPlatform.Common.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\Microsoft.Win32.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\Microsoft.Win32.Registry.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.win32.systemevents\6.0.0\lib\net6.0\Microsoft.Win32.SystemEvents.dll"
#r @"C:\Users\rvino\.nuget\packages\mysqlconnector\2.1.12\lib\net6.0\MySqlConnector.dll"
#r @"C:\Users\rvino\.nuget\packages\newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll"
#r @"C:\Users\rvino\.nuget\packages\npgsql\7.0.0\lib\net7.0\Npgsql.dll"
#r @"C:\Users\rvino\.nuget\packages\nuget.frameworks\5.11.0\lib\netstandard2.0\NuGet.Frameworks.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.0.2\lib\netstandard2.0\OSExtensions.dll"
#r @"C:\Users\rvino\.nuget\packages\perfolizer\0.2.1\lib\netstandard2.0\Perfolizer.dll"
#r @"C:\Users\rvino\.nuget\packages\rubjerg.graphviz\1.1.0\lib\netstandard2.0\Rubjerg.Graphviz.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.AppContext.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Buffers.dll"
#r @"C:\Users\rvino\.nuget\packages\system.codedom\6.0.0\lib\net6.0\System.CodeDom.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Collections.Concurrent.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Collections.Immutable.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Collections.NonGeneric.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Collections.Specialized.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Collections.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.Annotations.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.DataAnnotations.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.EventBasedAsync.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.TypeConverter.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ComponentModel.dll"
#r @"C:\Users\rvino\.nuget\packages\system.configuration.configurationmanager\6.0.0\lib\net6.0\System.Configuration.ConfigurationManager.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Configuration.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Console.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Core.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Data.Common.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Data.DataSetExtensions.dll"
#r @"C:\Users\rvino\.nuget\packages\system.data.sqlite.ef6\1.0.116\lib\netstandard2.1\System.Data.SQLite.EF6.dll"
#r @"C:\Users\rvino\.nuget\packages\stub.system.data.sqlite.core.netstandard\1.0.116\lib\netstandard2.1\System.Data.SQLite.dll"
#r @"C:\Users\rvino\.nuget\packages\system.data.sqlclient\4.8.3\ref\netcoreapp2.1\System.Data.SqlClient.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Data.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.Contracts.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.Debug.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.DiagnosticSource.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.FileVersionInfo.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.Process.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.StackTrace.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.TextWriterTraceListener.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.Tools.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.TraceSource.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Diagnostics.Tracing.dll"
#r @"C:\Users\rvino\.nuget\packages\system.drawing.common\6.0.0\lib\net6.0\System.Drawing.Common.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Drawing.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Drawing.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Dynamic.Runtime.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Formats.Asn1.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Formats.Tar.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Globalization.Calendars.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Globalization.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Globalization.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Compression.Brotli.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Compression.FileSystem.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Compression.ZipFile.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Compression.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.FileSystem.AccessControl.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.FileSystem.DriveInfo.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.FileSystem.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.FileSystem.Watcher.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.FileSystem.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.IsolatedStorage.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.MemoryMappedFiles.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Pipes.AccessControl.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.Pipes.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.UnmanagedMemoryStream.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.IO.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Linq.Expressions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Linq.Parallel.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Linq.Queryable.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Linq.dll"
#r @"C:\Users\rvino\.nuget\packages\system.management\6.0.0\lib\net6.0\System.Management.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Memory.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Http.Json.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Http.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.HttpListener.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Mail.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.NameResolution.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.NetworkInformation.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Ping.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Quic.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Requests.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Security.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.ServicePoint.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.Sockets.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.WebClient.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.WebHeaderCollection.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.WebProxy.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.WebSockets.Client.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.WebSockets.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Net.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Numerics.Vectors.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Numerics.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ObjectModel.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.DispatchProxy.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Emit.ILGeneration.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Emit.Lightweight.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Emit.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Metadata.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.TypeExtensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Reflection.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Resources.Reader.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Resources.ResourceManager.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Resources.Writer.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.CompilerServices.Unsafe.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.CompilerServices.VisualC.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Handles.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.InteropServices.JavaScript.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.InteropServices.RuntimeInformation.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.InteropServices.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Intrinsics.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Loader.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Numerics.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Serialization.Formatters.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Serialization.Json.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Serialization.Primitives.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Serialization.Xml.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.Serialization.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Runtime.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.AccessControl.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Claims.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.Algorithms.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.Cng.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.Csp.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.Encoding.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.OpenSsl.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.Primitives.dll"
#r @"C:\Users\rvino\.nuget\packages\system.security.cryptography.protecteddata\6.0.0\lib\net6.0\System.Security.Cryptography.ProtectedData.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.X509Certificates.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Cryptography.dll"
#r @"C:\Users\rvino\.nuget\packages\system.security.permissions\6.0.0\lib\net6.0\System.Security.Permissions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Principal.Windows.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.Principal.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.SecureString.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Security.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ServiceModel.Web.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ServiceProcess.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.Encoding.CodePages.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.Encoding.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.Encoding.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.Encodings.Web.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.Json.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Text.RegularExpressions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Channels.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Overlapped.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Tasks.Dataflow.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Tasks.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Tasks.Parallel.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Tasks.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Thread.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.ThreadPool.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.Timer.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Threading.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Transactions.Local.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Transactions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.ValueTuple.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Web.HttpUtility.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Web.dll"
#r @"C:\Users\rvino\.nuget\packages\system.windows.extensions\6.0.0\lib\net6.0\System.Windows.Extensions.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Windows.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.Linq.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.ReaderWriter.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.Serialization.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.XDocument.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.XPath.XDocument.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.XPath.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.XmlDocument.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.XmlSerializer.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.Xml.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\System.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.0.2\lib\netstandard2.0\TraceReloggerLib.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\WindowsBase.dll"
#r @"c:\prj\ai\fsharp\modules\applying_stencils\bin\Debug\net7.0\applying_stencils.dll"
#r @"c:\prj\ai\fsharp\basic_data_structures\bin\Debug\net7.0\basic_data_structures.dll"
#r @"c:\prj\ai\modules\applying_stencils\enumerating_combinations\bin\Debug\net6.0\enumerating_combinations.dll"
#r @"c:\prj\ai\fsharp\io\bin\Debug\net7.0\io.dll"
#r @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\ref\net7.0\netstandard.dll"
#r @"C:\Users\rvino\.nuget\packages\nunit\3.13.3\lib\netstandard2.0\nunit.framework.dll"
#r @"c:\prj\ai\fsharp\provided_data\bin\Debug\net7.0\provided_data.dll"
#r @"C:\Users\rvino\.nuget\packages\microsoft.testplatform.testhost\17.4.0\lib\netcoreapp3.1\testhost.dll"
#r @"C:\Users\rvino\.nuget\packages\xunit.abstractions\2.0.3\lib\netstandard2.0\xunit.abstractions.dll"
#r @"C:\Users\rvino\.nuget\packages\xunit.assert\2.4.2\lib\netstandard1.1\xunit.assert.dll"
#r @"C:\Users\rvino\.nuget\packages\xunit.extensibility.core\2.4.2\lib\netstandard1.1\xunit.core.dll"
#r @"C:\Users\rvino\.nuget\packages\xunit.extensibility.execution\2.4.2\lib\netstandard1.1\xunit.execution.dotnet.dll"
#load @"c:\prj\ai\fsharp\modules\finding_sequences\src\finding_repeated_pairs.fs"
#load @"c:\prj\ai\fsharp\modules\finding_sequences\src\finding_many_repetitions.fs"
#load @"c:\prj\ai\fsharp\modules\finding_sequences\src\finding_repetitions_with_concepts.fs"
#load @"c:\prj\ai\fsharp\modules\finding_sequences\src\test\finding_a_sequence.fs"
#load @"c:\prj\ai\fsharp\modules\finding_sequences\src\test\finding_sequences_in_history.fs"
#load @"c:\Users\rvino\.nuget\packages\microsoft.net.test.sdk\17.4.0\build\netcoreapp3.1\Microsoft.NET.Test.Sdk.Program.fs"
open rvinowise.ai
open rvinowise.extensions
;;
